version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www
      - ./storage/app/projetpedagogie.json:/home/smt/Bureau/pedagogie-laravel/storage/app/projetpedagogie.json
    networks:
      - laravel
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres  # Nom du service PostgreSQL
      DB_PORT: 5432
      DB_DATABASE: pedagogie-laravel
      DB_USERNAME: postgres
      DB_PASSWORD: Passer123

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel

  postgres:  # Service PostgreSQL
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: pedagogie-laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Passer123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:  # Volume persistant pour les données PostgreSQL
